// Action, Adventure, Animation, Biography, Comedy, Crime, Documentary, Drama, Family, Fantasy, History,
// Horror, Music, Musical, Mystery, Romance, SciFi, Sport, Thriller, War, Western

export const Categories = [
  { label: "African", value: "african" },
  { label: "Action", value: "action" },
  { label: "Adventure", value: "adventure" },
  { label: "Animation", value: "animation" },
  { label: "Biography", value: "biography" },
  { label: "Cartoon", value: "cartoon" },
  { label: "Comedy", value: "comedy" },
  { label: "Crime", value: "crime" },
  { label: "Documentary", value: "cocumentary" },
  { label: "Drama", value: "drama" },
  { label: "Eastern", value: "eastern" },
  { label: "Family", value: "family" },
  { label: "Fantasy", value: "fantasy" },
  { label: "History", value: "history" },
  { label: "Horror", value: "horror" },
  { label: "Music", value: "music" },
  { label: "Musical", value: "musical" },
  { label: "Mystery", value: "mystery" },
  { label: "Romance", value: "romance" },
  { label: "SciFi", value: "scifi" },
  { label: "Sport", value: "sport" },
  { label: "Thriller", value: "thriller" },
  { label: "War", value: "war" },
  { label: "Western", value: "western" },
];
